language: node_js
node_js:
- '0.12'
before_install:
- gem install sass
- npm install -g grunt-cli
- npm install -g bower
- bower install
script: npm run travis
env:
  global:
  - secure: "ruogbCgGbexOTJ9+tP0eP6R0DjC42/9EFUdAuH7KZzLqhB5rR3/x/YwQ+Cj0ZwRb4JJCAOHYZiuFfEvnXEU7QruU9HXIC2yqGvSolyr2vS2oEvPWHbANYrutm6fiOplq2DkgQTxLPNCCstArR3iBUXMll6esFDj/3vJXr1YfZrg="
